"""Regression tests for BF-11/BF-13: HTML handling in the PDF renderer.

BF-11 established that raw HTML tags from model output must not appear as escaped
literal text (e.g. &lt;div&gt;) in the PDF.

BF-13 changes the strategy: instead of stripping HTML tags before rendering,
markdown-it is now configured with html=True so that raw HTML from the model
(e.g. <div align="center">) passes through to WeasyPrint intact. WeasyPrint then
renders the HTML natively, preserving centering, bold, and other styling.

Tests in this module verify the pass-through behaviour through the public render()
interface, inspecting the HTML string that WeasyPrintRenderer constructs and passes
to WeasyPrint.
"""

from __future__ import annotations

from pathlib import Path
from unittest.mock import MagicMock, patch

import pytest

from jsa.render.weasy import WeasyPrintRenderer


# ---------------------------------------------------------------------------
# Helper fixture: captures the HTML string WeasyPrint sees, without calling
# the real WeasyPrint library.
# ---------------------------------------------------------------------------


@pytest.fixture
def mock_weasyprint():
    """Patch weasyprint.HTML and return the mock so tests can inspect calls."""
    with patch("weasyprint.HTML") as mock_html:
        yield mock_html


# ---------------------------------------------------------------------------
# BF-11/BF-13 HTML pass-through tests
# ---------------------------------------------------------------------------


class TestHtmlPassThroughRendering:
    async def test_div_tag_passed_through_text_preserved(
        self, tmp_path: Path, mock_weasyprint: MagicMock
    ) -> None:
        """<div align="center"> passes through to WeasyPrint; the name text is preserved.

        Pre-fix: markdown-it (html=False) would escape the tag as
        &lt;div align="center"&gt; — visible junk in the PDF.
        BF-13 fix: html=True lets the tag pass through intact; WeasyPrint renders it.
        """
        md = "<div align=\"center\">Jane Doe</div>"
        renderer = WeasyPrintRenderer()
        await renderer.render(md, tmp_path / "out.pdf")

        html_string = mock_weasyprint.call_args.kwargs["string"]

        # The text content must survive.
        assert "Jane Doe" in html_string
        # The tag passes through (html=True).
        assert "<div" in html_string
        # The escaped form must be absent (proves the tag was not escaped).
        assert "&lt;div" not in html_string

    async def test_multiple_inline_tags_passed_through(
        self, tmp_path: Path, mock_weasyprint: MagicMock
    ) -> None:
        """Multiple raw HTML tags (e.g. <br>) pass through to WeasyPrint."""
        md = "# Hello\n<br>\nworld"
        renderer = WeasyPrintRenderer()
        await renderer.render(md, tmp_path / "out.pdf")

        html_string = mock_weasyprint.call_args.kwargs["string"]

        # With html=True, <br> passes through rather than being stripped.
        assert "<br" in html_string
        # The escaped form must be absent (proves the tag was not escaped).
        assert "&lt;br" not in html_string
        # The heading text must be present.
        assert "Hello" in html_string

    async def test_heading_tag_passed_through(
        self, tmp_path: Path, mock_weasyprint: MagicMock
    ) -> None:
        """A raw <h1> tag in the markdown input passes through to WeasyPrint.

        With html=True, markdown-it treats <h1>...</h1> as an HTML block and
        passes it through intact. WeasyPrint renders it as a real h1 element.
        """
        md = "<h1>Raw heading tag</h1>"
        renderer = WeasyPrintRenderer()
        await renderer.render(md, tmp_path / "out.pdf")

        html_string = mock_weasyprint.call_args.kwargs["string"]

        # The text inside the tag must be present in the output.
        assert "Raw heading tag" in html_string
        # The tag passes through (html=True); WeasyPrint sees a real h1.
        assert "<h1>" in html_string

    async def test_clean_markdown_unaffected(
        self, tmp_path: Path, mock_weasyprint: MagicMock
    ) -> None:
        """Markdown with no raw HTML tags is rendered normally with html=True.

        The pass-through setting must not disturb markdown-generated HTML tags
        (<h1>, <strong>). These are generated by markdown-it from the source
        markdown — there is no pre-render strip.
        """
        md = "# Title\n\n**bold** and _italic_"
        renderer = WeasyPrintRenderer()
        await renderer.render(md, tmp_path / "out.pdf")

        html_string = mock_weasyprint.call_args.kwargs["string"]

        # Generated HTML from markdown-it must still be present.
        assert "<h1>" in html_string
        assert "<strong>" in html_string

    async def test_table_still_renders(
        self, tmp_path: Path, mock_weasyprint: MagicMock
    ) -> None:
        """GFM table syntax is rendered correctly.

        Table rows/cells contain no <...> in source Markdown, so there is
        nothing for any processor to handle. Generated <table> HTML must still
        appear in the output passed to WeasyPrint.
        """
        md = (
            "| Name  | Score |\n"
            "| ----- | ----- |\n"
            "| Alice | 95    |\n"
        )
        renderer = WeasyPrintRenderer()
        await renderer.render(md, tmp_path / "out.pdf")

        html_string = mock_weasyprint.call_args.kwargs["string"]
        assert "<table>" in html_string

    async def test_mixed_html_and_markdown(
        self, tmp_path: Path, mock_weasyprint: MagicMock
    ) -> None:
        """Markdown mixed with raw HTML: HTML passes through, markdown structure preserved."""
        md = (
            "<div align=\"center\">Jane Doe</div>\n\n"
            "## Experience\n\n"
            "- Did **great** work\n"
        )
        renderer = WeasyPrintRenderer()
        await renderer.render(md, tmp_path / "out.pdf")

        html_string = mock_weasyprint.call_args.kwargs["string"]

        # Raw div tag passes through (html=True).
        assert "<div" in html_string
        assert "&lt;div" not in html_string
        # Content preserved.
        assert "Jane Doe" in html_string
        # Markdown-generated structure preserved.
        assert "<h2>" in html_string
        assert "<strong>" in html_string

    async def test_no_tags_input_is_noop(
        self, tmp_path: Path, mock_weasyprint: MagicMock
    ) -> None:
        """Markdown with no HTML tags passes through markdown-it with html=True unchanged."""
        md = "No tags here"
        renderer = WeasyPrintRenderer()
        await renderer.render(md, tmp_path / "out.pdf")

        html_string = mock_weasyprint.call_args.kwargs["string"]

        assert "No tags here" in html_string

    async def test_autolink_email_preserved(
        self, tmp_path: Path, mock_weasyprint: MagicMock
    ) -> None:
        """CommonMark autolink <jane.doe@example.com> is preserved.

        markdown-it with html=True still parses autolinks via CommonMark rules
        before HTML handling — the email autolink renders as a mailto anchor.
        """
        md = "<jane.doe@example.com>"
        renderer = WeasyPrintRenderer()
        await renderer.render(md, tmp_path / "out.pdf")

        html_string = mock_weasyprint.call_args.kwargs["string"]

        # The email address must survive in the rendered output.
        assert "jane.doe@example.com" in html_string
        # markdown-it renders CommonMark autolinks as <a href="mailto:..."> anchors.
        assert "mailto:" in html_string

    async def test_prose_comparison_preserved(
        self, tmp_path: Path, mock_weasyprint: MagicMock
    ) -> None:
        """Prose with bare comparison operators (<, >) is preserved.

        markdown-it treats <2% as literal text (not a valid HTML tag — tags require
        a letter after <) and encodes it as &lt;2% in the output, which displays
        as <2%.
        """
        md = "Error rate <2% and throughput >3x"
        renderer = WeasyPrintRenderer()
        await renderer.render(md, tmp_path / "out.pdf")

        html_string = mock_weasyprint.call_args.kwargs["string"]

        # Both sides of the comparison operators must appear in the rendered output.
        assert "2%" in html_string
        assert "3x" in html_string
